In [152]:
import os
import json
import requests
import pandas as pd
from mysql import connector 
from dotenv import load_dotenv

In [153]:
load_dotenv()

True

In [154]:
API_KEY = os.getenv("API_KEY")
API_HOST = os.getenv("API_HOST")
SEASON = 2024
LEAGUE_ID = 39

In [155]:
url = "https://v3.football.api-sports.io/standings"

headers = {
	"x-rapidapi-key": API_KEY,
	"x-rapidapi-host": API_HOST
}

querystring = {"league":LEAGUE_ID,
               "season":SEASON}

In [156]:
print(querystring)

{'league': 39, 'season': 2024}

In [157]:
response = requests.get(url, headers=headers, params=querystring)

In [158]:
payload = response.json()

In [159]:
payload

{'get': 'standings',
 'parameters': {'league': '39', 'season': '2024'},
 'errors': [],
 'results': 1,
 'paging': {'current': 1, 'total': 1},
 'response': [{'league': {'id': 39,
    'name': 'Premier League',
    'country': 'England',
    'logo': 'https://media.api-sports.io/football/leagues/39.png',
    'flag': 'https://media.api-sports.io/flags/gb-eng.svg',
    'season': 2024,
    'standings': [[{'rank': 1,
       'team': {'id': 40,
        'name': 'Liverpool',
        'logo': 'https://media.api-sports.io/football/teams/40.png'},
       'points': 84,
       'goalsDiff': 45,
       'group': 'Premier League',
       'form': 'DLDLW',
       'status': 'same',
       'description': 'Champions League',
       'all': {'played': 38,
        'win': 25,
        'draw': 9,
        'lose': 4,
        'goals': {'for': 86, 'against': 41}},
       'home': {'played': 19,
        'win': 14,
        'draw': 4,
        'lose': 1,
        'goals': {'for': 42, 'against': 16}},
       'away': {'played': 19,
        'win': 11,
        'draw': 5,
        'lose': 3,
        'goals': {'for': 44, 'against': 25}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 2,
       'team': {'id': 42,
        'name': 'Arsenal',
        'logo': 'https://media.api-sports.io/football/teams/42.png'},
       'points': 74,
       'goalsDiff': 35,
       'group': 'Premier League',
       'form': 'WWDLD',
       'status': 'same',
       'description': 'Champions League',
       'all': {'played': 38,
        'win': 20,
        'draw': 14,
        'lose': 4,
        'goals': {'for': 69, 'against': 34}},
       'home': {'played': 19,
        'win': 11,
        'draw': 6,
        'lose': 2,
        'goals': {'for': 35, 'against': 17}},
       'away': {'played': 19,
        'win': 9,
        'draw': 8,
        'lose': 2,
        'goals': {'for': 34, 'against': 17}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 3,
       'team': {'id': 50,
        'name': 'Manchester City',
        'logo': 'https://media.api-sports.io/football/teams/50.png'},
       'points': 71,
       'goalsDiff': 28,
       'group': 'Premier League',
       'form': 'WWDWW',
       'status': 'same',
       'description': 'Champions League',
       'all': {'played': 38,
        'win': 21,
        'draw': 8,
        'lose': 9,
        'goals': {'for': 72, 'against': 44}},
       'home': {'played': 19,
        'win': 13,
        'draw': 3,
        'lose': 3,
        'goals': {'for': 43, 'against': 23}},
       'away': {'played': 19,
        'win': 8,
        'draw': 5,
        'lose': 6,
        'goals': {'for': 29, 'against': 21}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 4,
       'team': {'id': 49,
        'name': 'Chelsea',
        'logo': 'https://media.api-sports.io/football/teams/49.png'},
       'points': 69,
       'goalsDiff': 21,
       'group': 'Premier League',
       'form': 'WWLWW',
       'status': 'same',
       'description': 'Champions League',
       'all': {'played': 38,
        'win': 20,
        'draw': 9,
        'lose': 9,
        'goals': {'for': 64, 'against': 43}},
       'home': {'played': 19,
        'win': 12,
        'draw': 5,
        'lose': 2,
        'goals': {'for': 35, 'against': 18}},
       'away': {'played': 19,
        'win': 8,
        'draw': 4,
        'lose': 7,
        'goals': {'for': 29, 'against': 25}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 5,
       'team': {'id': 34,
        'name': 'Newcastle',
        'logo': 'https://media.api-sports.io/football/teams/34.png'},
       'points': 66,
       'goalsDiff': 21,
       'group': 'Premier League',
       'form': 'LLWDW',
       'status': 'same',
       'description': 'Champions League',
       'all': {'played': 38,
        'win': 20,
        'draw': 6,
        'lose': 12,
        'goals': {'for': 68, 'against': 47}},
       'home': {'played': 19,
        'win': 12,
        'draw': 2,
        'lose': 5,
        'goals': {'for': 40, 'against': 20}},
       'away': {'played': 19,
        'win': 8,
        'draw': 4,
        'lose': 7,
        'goals': {'for': 28, 'against': 27}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 6,
       'team': {'id': 66,
        'name': 'Aston Villa',
        'logo': 'https://media.api-sports.io/football/teams/66.png'},
       'points': 66,
       'goalsDiff': 7,
       'group': 'Premier League',
       'form': 'LWWWL',
       'status': 'same',
       'description': 'UEFA Europa League',
       'all': {'played': 38,
        'win': 19,
        'draw': 9,
        'lose': 10,
        'goals': {'for': 58, 'against': 51}},
       'home': {'played': 19,
        'win': 11,
        'draw': 7,
        'lose': 1,
        'goals': {'for': 34, 'against': 20}},
       'away': {'played': 19,
        'win': 8,
        'draw': 2,
        'lose': 9,
        'goals': {'for': 24, 'against': 31}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 7,
       'team': {'id': 65,
        'name': 'Nottingham Forest',
        'logo': 'https://media.api-sports.io/football/teams/65.png'},
       'points': 65,
       'goalsDiff': 12,
       'group': 'Premier League',
       'form': 'LWDDL',
       'status': 'same',
       'description': 'Conference League Qualification',
       'all': {'played': 38,
        'win': 19,
        'draw': 8,
        'lose': 11,
        'goals': {'for': 58, 'against': 46}},
       'home': {'played': 19,
        'win': 9,
        'draw': 5,
        'lose': 5,
        'goals': {'for': 26, 'against': 16}},
       'away': {'played': 19,
        'win': 10,
        'draw': 3,
        'lose': 6,
        'goals': {'for': 32, 'against': 30}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 8,
       'team': {'id': 51,
        'name': 'Brighton',
        'logo': 'https://media.api-sports.io/football/teams/51.png'},
       'points': 61,
       'goalsDiff': 7,
       'group': 'Premier League',
       'form': 'WWWDW',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 16,
        'draw': 13,
        'lose': 9,
        'goals': {'for': 66, 'against': 59}},
       'home': {'played': 19,
        'win': 8,
        'draw': 8,
        'lose': 3,
        'goals': {'for': 30, 'against': 26}},
       'away': {'played': 19,
        'win': 8,
        'draw': 5,
        'lose': 6,
        'goals': {'for': 36, 'against': 33}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 9,
       'team': {'id': 35,
        'name': 'Bournemouth',
        'logo': 'https://media.api-sports.io/football/teams/35.png'},
       'points': 56,
       'goalsDiff': 12,
       'group': 'Premier League',
       'form': 'WLLWD',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 15,
        'draw': 11,
        'lose': 12,
        'goals': {'for': 58, 'against': 46}},
       'home': {'played': 19,
        'win': 8,
        'draw': 4,
        'lose': 7,
        'goals': {'for': 23, 'against': 16}},
       'away': {'played': 19,
        'win': 7,
        'draw': 7,
        'lose': 5,
        'goals': {'for': 35, 'against': 30}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 10,
       'team': {'id': 55,
        'name': 'Brentford',
        'logo': 'https://media.api-sports.io/football/teams/55.png'},
       'points': 56,
       'goalsDiff': 9,
       'group': 'Premier League',
       'form': 'DLWWW',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 16,
        'draw': 8,
        'lose': 14,
        'goals': {'for': 66, 'against': 57}},
       'home': {'played': 19,
        'win': 9,
        'draw': 4,
        'lose': 6,
        'goals': {'for': 40, 'against': 35}},
       'away': {'played': 19,
        'win': 7,
        'draw': 4,
        'lose': 8,
        'goals': {'for': 26, 'against': 22}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 11,
       'team': {'id': 36,
        'name': 'Fulham',
        'logo': 'https://media.api-sports.io/football/teams/36.png'},
       'points': 54,
       'goalsDiff': 0,
       'group': 'Premier League',
       'form': 'LWLLW',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 15,
        'draw': 9,
        'lose': 14,
        'goals': {'for': 54, 'against': 54}},
       'home': {'played': 19,
        'win': 7,
        'draw': 5,
        'lose': 7,
        'goals': {'for': 27, 'against': 30}},
       'away': {'played': 19,
        'win': 8,
        'draw': 4,
        'lose': 7,
        'goals': {'for': 27, 'against': 24}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 12,
       'team': {'id': 52,
        'name': 'Crystal Palace',
        'logo': 'https://media.api-sports.io/football/teams/52.png'},
       'points': 53,
       'goalsDiff': 0,
       'group': 'Premier League',
       'form': 'DWWDD',
       'status': 'same',
       'description': 'UEFA Europa League',
       'all': {'played': 38,
        'win': 13,
        'draw': 14,
        'lose': 11,
        'goals': {'for': 51, 'against': 51}},
       'home': {'played': 19,
        'win': 6,
        'draw': 7,
        'lose': 6,
        'goals': {'for': 24, 'against': 26}},
       'away': {'played': 19,
        'win': 7,
        'draw': 7,
        'lose': 5,
        'goals': {'for': 27, 'against': 25}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 13,
       'team': {'id': 45,
        'name': 'Everton',
        'logo': 'https://media.api-sports.io/football/teams/45.png'},
       'points': 48,
       'goalsDiff': -2,
       'group': 'Premier League',
       'form': 'WWWDL',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 11,
        'draw': 15,
        'lose': 12,
        'goals': {'for': 42, 'against': 44}},
       'home': {'played': 19,
        'win': 5,
        'draw': 9,
        'lose': 5,
        'goals': {'for': 26, 'against': 23}},
       'away': {'played': 19,
        'win': 6,
        'draw': 6,
        'lose': 7,
        'goals': {'for': 16, 'against': 21}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 14,
       'team': {'id': 48,
        'name': 'West Ham',
        'logo': 'https://media.api-sports.io/football/teams/48.png'},
       'points': 43,
       'goalsDiff': -16,
       'group': 'Premier League',
       'form': 'WLWDL',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 11,
        'draw': 10,
        'lose': 17,
        'goals': {'for': 46, 'against': 62}},
       'home': {'played': 19,
        'win': 5,
        'draw': 5,
        'lose': 9,
        'goals': {'for': 23, 'against': 34}},
       'away': {'played': 19,
        'win': 6,
        'draw': 5,
        'lose': 8,
        'goals': {'for': 23, 'against': 28}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 15,
       'team': {'id': 33,
        'name': 'Manchester United',
        'logo': 'https://media.api-sports.io/football/teams/33.png'},
       'points': 42,
       'goalsDiff': -10,
       'group': 'Premier League',
       'form': 'WLLLD',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 11,
        'draw': 9,
        'lose': 18,
        'goals': {'for': 44, 'against': 54}},
       'home': {'played': 19,
        'win': 7,
        'draw': 3,
        'lose': 9,
        'goals': {'for': 23, 'against': 28}},
       'away': {'played': 19,
        'win': 4,
        'draw': 6,
        'lose': 9,
        'goals': {'for': 21, 'against': 26}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 16,
       'team': {'id': 39,
        'name': 'Wolves',
        'logo': 'https://media.api-sports.io/football/teams/39.png'},
       'points': 42,
       'goalsDiff': -15,
       'group': 'Premier League',
       'form': 'DLLLW',
       'status': 'same',
       'description': None,
       'all': {'played': 38,
        'win': 12,
        'draw': 6,
        'lose': 20,
        'goals': {'for': 54, 'against': 69}},
       'home': {'played': 19,
        'win': 6,
        'draw': 3,
        'lose': 10,
        'goals': {'for': 27, 'against': 32}},
       'away': {'played': 19,
        'win': 6,
        'draw': 3,
        'lose': 10,
        'goals': {'for': 27, 'against': 37}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 17,
       'team': {'id': 47,
        'name': 'Tottenham',
        'logo': 'https://media.api-sports.io/football/teams/47.png'},
       'points': 38,
       'goalsDiff': -1,
       'group': 'Premier League',
       'form': 'LLLDL',
       'status': 'same',
       'description': 'Champions League',
       'all': {'played': 38,
        'win': 11,
        'draw': 5,
        'lose': 22,
        'goals': {'for': 64, 'against': 65}},
       'home': {'played': 19,
        'win': 6,
        'draw': 3,
        'lose': 10,
        'goals': {'for': 35, 'against': 35}},
       'away': {'played': 19,
        'win': 5,
        'draw': 2,
        'lose': 12,
        'goals': {'for': 29, 'against': 30}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 18,
       'team': {'id': 46,
        'name': 'Leicester',
        'logo': 'https://media.api-sports.io/football/teams/46.png'},
       'points': 25,
       'goalsDiff': -47,
       'group': 'Premier League',
       'form': 'LWDWL',
       'status': 'same',
       'description': 'Relegation',
       'all': {'played': 38,
        'win': 6,
        'draw': 7,
        'lose': 25,
        'goals': {'for': 33, 'against': 80}},
       'home': {'played': 19,
        'win': 4,
        'draw': 3,
        'lose': 12,
        'goals': {'for': 15, 'against': 34}},
       'away': {'played': 19,
        'win': 2,
        'draw': 4,
        'lose': 13,
        'goals': {'for': 18, 'against': 46}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 19,
       'team': {'id': 57,
        'name': 'Ipswich',
        'logo': 'https://media.api-sports.io/football/teams/57.png'},
       'points': 22,
       'goalsDiff': -46,
       'group': 'Premier League',
       'form': 'LLLDL',
       'status': 'same',
       'description': 'Relegation',
       'all': {'played': 38,
        'win': 4,
        'draw': 10,
        'lose': 24,
        'goals': {'for': 36, 'against': 82}},
       'home': {'played': 19,
        'win': 1,
        'draw': 4,
        'lose': 14,
        'goals': {'for': 14, 'against': 44}},
       'away': {'played': 19,
        'win': 3,
        'draw': 6,
        'lose': 10,
        'goals': {'for': 22, 'against': 38}},
       'update': '2025-05-26T00:00:00+00:00'},
      {'rank': 20,
       'team': {'id': 41,
        'name': 'Southampton',
        'logo': 'https://media.api-sports.io/football/teams/41.png'},
       'points': 12,
       'goalsDiff': -60,
       'group': 'Premier League',
       'form': 'LLDLL',
       'status': 'same',
       'description': 'Relegation',
       'all': {'played': 38,
        'win': 2,
        'draw': 6,
        'lose': 30,
        'goals': {'for': 26, 'against': 86}},
       'home': {'played': 19,
        'win': 1,
        'draw': 3,
        'lose': 15,
        'goals': {'for': 13, 'against': 47}},
       'away': {'played': 19,
        'win': 1,
        'draw': 3,
        'lose': 15,
        'goals': {'for': 13, 'against': 39}},
       'update': '2025-05-26T00:00:00+00:00'}]]}}]}

In [160]:
formatted_response = json.dumps(payload, indent=4 )

In [161]:
print(formatted_response)

{
    "get": "standings",
    "parameters": {
        "league": "39",
        "season": "2024"
    },
    "errors": [],
    "results": 1,
    "paging": {
        "current": 1,
        "total": 1
    },
    "response": [
        {
            "league": {
                "id": 39,
                "name": "Premier League",
                "country": "England",
                "logo": "https://media.api-sports.io/football/leagues/39.png",
                "flag": "https://media.api-sports.io/flags/gb-eng.svg",
                "season": 2024,
                "standings": [
                    [
                        {
                            "rank": 1,
                            "team": {
                                "id": 40,
                                "name": "Liverpool",
                                "logo": "https://media.api-sports.io/football/teams/40.png"
                            },
                            "points": 84,
                            "goalsDiff": 45,
                            "group": "Premier League",
                            "form": "DLDLW",
                            "status": "same",
                            "description": "Champions League",
                            "all": {
                                "played": 38,
                                "win": 25,
                                "draw": 9,
                                "lose": 4,
                                "goals": {
                                    "for": 86,
                                    "against": 41
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 14,
                                "draw": 4,
                                "lose": 1,
                                "goals": {
                                    "for": 42,
                                    "against": 16
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 11,
                                "draw": 5,
                                "lose": 3,
                                "goals": {
                                    "for": 44,
                                    "against": 25
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 2,
                            "team": {
                                "id": 42,
                                "name": "Arsenal",
                                "logo": "https://media.api-sports.io/football/teams/42.png"
                            },
                            "points": 74,
                            "goalsDiff": 35,
                            "group": "Premier League",
                            "form": "WWDLD",
                            "status": "same",
                            "description": "Champions League",
                            "all": {
                                "played": 38,
                                "win": 20,
                                "draw": 14,
                                "lose": 4,
                                "goals": {
                                    "for": 69,
                                    "against": 34
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 11,
                                "draw": 6,
                                "lose": 2,
                                "goals": {
                                    "for": 35,
                                    "against": 17
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 9,
                                "draw": 8,
                                "lose": 2,
                                "goals": {
                                    "for": 34,
                                    "against": 17
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 3,
                            "team": {
                                "id": 50,
                                "name": "Manchester City",
                                "logo": "https://media.api-sports.io/football/teams/50.png"
                            },
                            "points": 71,
                            "goalsDiff": 28,
                            "group": "Premier League",
                            "form": "WWDWW",
                            "status": "same",
                            "description": "Champions League",
                            "all": {
                                "played": 38,
                                "win": 21,
                                "draw": 8,
                                "lose": 9,
                                "goals": {
                                    "for": 72,
                                    "against": 44
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 13,
                                "draw": 3,
                                "lose": 3,
                                "goals": {
                                    "for": 43,
                                    "against": 23
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 8,
                                "draw": 5,
                                "lose": 6,
                                "goals": {
                                    "for": 29,
                                    "against": 21
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 4,
                            "team": {
                                "id": 49,
                                "name": "Chelsea",
                                "logo": "https://media.api-sports.io/football/teams/49.png"
                            },
                            "points": 69,
                            "goalsDiff": 21,
                            "group": "Premier League",
                            "form": "WWLWW",
                            "status": "same",
                            "description": "Champions League",
                            "all": {
                                "played": 38,
                                "win": 20,
                                "draw": 9,
                                "lose": 9,
                                "goals": {
                                    "for": 64,
                                    "against": 43
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 12,
                                "draw": 5,
                                "lose": 2,
                                "goals": {
                                    "for": 35,
                                    "against": 18
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 8,
                                "draw": 4,
                                "lose": 7,
                                "goals": {
                                    "for": 29,
                                    "against": 25
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 5,
                            "team": {
                                "id": 34,
                                "name": "Newcastle",
                                "logo": "https://media.api-sports.io/football/teams/34.png"
                            },
                            "points": 66,
                            "goalsDiff": 21,
                            "group": "Premier League",
                            "form": "LLWDW",
                            "status": "same",
                            "description": "Champions League",
                            "all": {
                                "played": 38,
                                "win": 20,
                                "draw": 6,
                                "lose": 12,
                                "goals": {
                                    "for": 68,
                                    "against": 47
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 12,
                                "draw": 2,
                                "lose": 5,
                                "goals": {
                                    "for": 40,
                                    "against": 20
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 8,
                                "draw": 4,
                                "lose": 7,
                                "goals": {
                                    "for": 28,
                                    "against": 27
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 6,
                            "team": {
                                "id": 66,
                                "name": "Aston Villa",
                                "logo": "https://media.api-sports.io/football/teams/66.png"
                            },
                            "points": 66,
                            "goalsDiff": 7,
                            "group": "Premier League",
                            "form": "LWWWL",
                            "status": "same",
                            "description": "UEFA Europa League",
                            "all": {
                                "played": 38,
                                "win": 19,
                                "draw": 9,
                                "lose": 10,
                                "goals": {
                                    "for": 58,
                                    "against": 51
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 11,
                                "draw": 7,
                                "lose": 1,
                                "goals": {
                                    "for": 34,
                                    "against": 20
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 8,
                                "draw": 2,
                                "lose": 9,
                                "goals": {
                                    "for": 24,
                                    "against": 31
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 7,
                            "team": {
                                "id": 65,
                                "name": "Nottingham Forest",
                                "logo": "https://media.api-sports.io/football/teams/65.png"
                            },
                            "points": 65,
                            "goalsDiff": 12,
                            "group": "Premier League",
                            "form": "LWDDL",
                            "status": "same",
                            "description": "Conference League Qualification",
                            "all": {
                                "played": 38,
                                "win": 19,
                                "draw": 8,
                                "lose": 11,
                                "goals": {
                                    "for": 58,
                                    "against": 46
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 9,
                                "draw": 5,
                                "lose": 5,
                                "goals": {
                                    "for": 26,
                                    "against": 16
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 10,
                                "draw": 3,
                                "lose": 6,
                                "goals": {
                                    "for": 32,
                                    "against": 30
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 8,
                            "team": {
                                "id": 51,
                                "name": "Brighton",
                                "logo": "https://media.api-sports.io/football/teams/51.png"
                            },
                            "points": 61,
                            "goalsDiff": 7,
                            "group": "Premier League",
                            "form": "WWWDW",
                            "status": "same",
                            "description": null,
                            "all": {
                                "played": 38,
                                "win": 16,
                                "draw": 13,
                                "lose": 9,
                                "goals": {
                                    "for": 66,
                                    "against": 59
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 8,
                                "draw": 8,
                                "lose": 3,
                                "goals": {
                                    "for": 30,
                                    "against": 26
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 8,
                                "draw": 5,
                                "lose": 6,
                                "goals": {
                                    "for": 36,
                                    "against": 33
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 9,
                            "team": {
                                "id": 35,
                                "name": "Bournemouth",
                                "logo": "https://media.api-sports.io/football/teams/35.png"
                            },
                            "points": 56,
                            "goalsDiff": 12,
                            "group": "Premier League",
                            "form": "WLLWD",
                            "status": "same",
                            "description": null,
                            "all": {
                                "played": 38,
                                "win": 15,
                                "draw": 11,
                                "lose": 12,
                                "goals": {
                                    "for": 58,
                                    "against": 46
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 8,
                                "draw": 4,
                                "lose": 7,
                                "goals": {
                                    "for": 23,
                                    "against": 16
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 7,
                                "draw": 7,
                                "lose": 5,
                                "goals": {
                                    "for": 35,
                                    "against": 30
                                }
                            },
                            "update": "2025-05-26T00:00:00+00:00"
                        },
                        {
                            "rank": 10,
                            "team": {
                                "id": 55,
                                "name": "Brentford",
                                "logo": "https://media.api-sports.io/football/teams/55.png"
                            },
                            "points": 56,
                            "goalsDiff": 9,
                            "group": "Premier League",
                            "form": "DLWWW",
                            "status": "same",
                            "description": null,
                            "all": {
                                "played": 38,
                                "win": 16,
                                "draw": 8,
                                "lose": 14,
                                "goals": {
                                    "for": 66,
                                    "against": 57
                                }
                            },
                            "home": {
                                "played": 19,
                                "win": 9,
                                "draw": 4,
                                "lose": 6,
                                "goals": {
                                    "for": 40,
                                    "against": 35
                                }
                            },
                            "away": {
                                "played": 19,
                                "win": 7,
                                "draw": 4,
                                "lose": 8,
                                "goals": {
                                    "for": 26,

In [162]:
standings_list = payload["response"][0]["league"]["standings"][0]
standings_list

[{'rank': 1,
  'team': {'id': 40,
   'name': 'Liverpool',
   'logo': 'https://media.api-sports.io/football/teams/40.png'},
  'points': 84,
  'goalsDiff': 45,
  'group': 'Premier League',
  'form': 'DLDLW',
  'status': 'same',
  'description': 'Champions League',
  'all': {'played': 38,
   'win': 25,
   'draw': 9,
   'lose': 4,
   'goals': {'for': 86, 'against': 41}},
  'home': {'played': 19,
   'win': 14,
   'draw': 4,
   'lose': 1,
   'goals': {'for': 42, 'against': 16}},
  'away': {'played': 19,
   'win': 11,
   'draw': 5,
   'lose': 3,
   'goals': {'for': 44, 'against': 25}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 2,
  'team': {'id': 42,
   'name': 'Arsenal',
   'logo': 'https://media.api-sports.io/football/teams/42.png'},
  'points': 74,
  'goalsDiff': 35,
  'group': 'Premier League',
  'form': 'WWDLD',
  'status': 'same',
  'description': 'Champions League',
  'all': {'played': 38,
   'win': 20,
   'draw': 14,
   'lose': 4,
   'goals': {'for': 69, 'against': 34}},
  'home': {'played': 19,
   'win': 11,
   'draw': 6,
   'lose': 2,
   'goals': {'for': 35, 'against': 17}},
  'away': {'played': 19,
   'win': 9,
   'draw': 8,
   'lose': 2,
   'goals': {'for': 34, 'against': 17}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 3,
  'team': {'id': 50,
   'name': 'Manchester City',
   'logo': 'https://media.api-sports.io/football/teams/50.png'},
  'points': 71,
  'goalsDiff': 28,
  'group': 'Premier League',
  'form': 'WWDWW',
  'status': 'same',
  'description': 'Champions League',
  'all': {'played': 38,
   'win': 21,
   'draw': 8,
   'lose': 9,
   'goals': {'for': 72, 'against': 44}},
  'home': {'played': 19,
   'win': 13,
   'draw': 3,
   'lose': 3,
   'goals': {'for': 43, 'against': 23}},
  'away': {'played': 19,
   'win': 8,
   'draw': 5,
   'lose': 6,
   'goals': {'for': 29, 'against': 21}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 4,
  'team': {'id': 49,
   'name': 'Chelsea',
   'logo': 'https://media.api-sports.io/football/teams/49.png'},
  'points': 69,
  'goalsDiff': 21,
  'group': 'Premier League',
  'form': 'WWLWW',
  'status': 'same',
  'description': 'Champions League',
  'all': {'played': 38,
   'win': 20,
   'draw': 9,
   'lose': 9,
   'goals': {'for': 64, 'against': 43}},
  'home': {'played': 19,
   'win': 12,
   'draw': 5,
   'lose': 2,
   'goals': {'for': 35, 'against': 18}},
  'away': {'played': 19,
   'win': 8,
   'draw': 4,
   'lose': 7,
   'goals': {'for': 29, 'against': 25}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 5,
  'team': {'id': 34,
   'name': 'Newcastle',
   'logo': 'https://media.api-sports.io/football/teams/34.png'},
  'points': 66,
  'goalsDiff': 21,
  'group': 'Premier League',
  'form': 'LLWDW',
  'status': 'same',
  'description': 'Champions League',
  'all': {'played': 38,
   'win': 20,
   'draw': 6,
   'lose': 12,
   'goals': {'for': 68, 'against': 47}},
  'home': {'played': 19,
   'win': 12,
   'draw': 2,
   'lose': 5,
   'goals': {'for': 40, 'against': 20}},
  'away': {'played': 19,
   'win': 8,
   'draw': 4,
   'lose': 7,
   'goals': {'for': 28, 'against': 27}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 6,
  'team': {'id': 66,
   'name': 'Aston Villa',
   'logo': 'https://media.api-sports.io/football/teams/66.png'},
  'points': 66,
  'goalsDiff': 7,
  'group': 'Premier League',
  'form': 'LWWWL',
  'status': 'same',
  'description': 'UEFA Europa League',
  'all': {'played': 38,
   'win': 19,
   'draw': 9,
   'lose': 10,
   'goals': {'for': 58, 'against': 51}},
  'home': {'played': 19,
   'win': 11,
   'draw': 7,
   'lose': 1,
   'goals': {'for': 34, 'against': 20}},
  'away': {'played': 19,
   'win': 8,
   'draw': 2,
   'lose': 9,
   'goals': {'for': 24, 'against': 31}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 7,
  'team': {'id': 65,
   'name': 'Nottingham Forest',
   'logo': 'https://media.api-sports.io/football/teams/65.png'},
  'points': 65,
  'goalsDiff': 12,
  'group': 'Premier League',
  'form': 'LWDDL',
  'status': 'same',
  'description': 'Conference League Qualification',
  'all': {'played': 38,
   'win': 19,
   'draw': 8,
   'lose': 11,
   'goals': {'for': 58, 'against': 46}},
  'home': {'played': 19,
   'win': 9,
   'draw': 5,
   'lose': 5,
   'goals': {'for': 26, 'against': 16}},
  'away': {'played': 19,
   'win': 10,
   'draw': 3,
   'lose': 6,
   'goals': {'for': 32, 'against': 30}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 8,
  'team': {'id': 51,
   'name': 'Brighton',
   'logo': 'https://media.api-sports.io/football/teams/51.png'},
  'points': 61,
  'goalsDiff': 7,
  'group': 'Premier League',
  'form': 'WWWDW',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 16,
   'draw': 13,
   'lose': 9,
   'goals': {'for': 66, 'against': 59}},
  'home': {'played': 19,
   'win': 8,
   'draw': 8,
   'lose': 3,
   'goals': {'for': 30, 'against': 26}},
  'away': {'played': 19,
   'win': 8,
   'draw': 5,
   'lose': 6,
   'goals': {'for': 36, 'against': 33}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 9,
  'team': {'id': 35,
   'name': 'Bournemouth',
   'logo': 'https://media.api-sports.io/football/teams/35.png'},
  'points': 56,
  'goalsDiff': 12,
  'group': 'Premier League',
  'form': 'WLLWD',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 15,
   'draw': 11,
   'lose': 12,
   'goals': {'for': 58, 'against': 46}},
  'home': {'played': 19,
   'win': 8,
   'draw': 4,
   'lose': 7,
   'goals': {'for': 23, 'against': 16}},
  'away': {'played': 19,
   'win': 7,
   'draw': 7,
   'lose': 5,
   'goals': {'for': 35, 'against': 30}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 10,
  'team': {'id': 55,
   'name': 'Brentford',
   'logo': 'https://media.api-sports.io/football/teams/55.png'},
  'points': 56,
  'goalsDiff': 9,
  'group': 'Premier League',
  'form': 'DLWWW',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 16,
   'draw': 8,
   'lose': 14,
   'goals': {'for': 66, 'against': 57}},
  'home': {'played': 19,
   'win': 9,
   'draw': 4,
   'lose': 6,
   'goals': {'for': 40, 'against': 35}},
  'away': {'played': 19,
   'win': 7,
   'draw': 4,
   'lose': 8,
   'goals': {'for': 26, 'against': 22}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 11,
  'team': {'id': 36,
   'name': 'Fulham',
   'logo': 'https://media.api-sports.io/football/teams/36.png'},
  'points': 54,
  'goalsDiff': 0,
  'group': 'Premier League',
  'form': 'LWLLW',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 15,
   'draw': 9,
   'lose': 14,
   'goals': {'for': 54, 'against': 54}},
  'home': {'played': 19,
   'win': 7,
   'draw': 5,
   'lose': 7,
   'goals': {'for': 27, 'against': 30}},
  'away': {'played': 19,
   'win': 8,
   'draw': 4,
   'lose': 7,
   'goals': {'for': 27, 'against': 24}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 12,
  'team': {'id': 52,
   'name': 'Crystal Palace',
   'logo': 'https://media.api-sports.io/football/teams/52.png'},
  'points': 53,
  'goalsDiff': 0,
  'group': 'Premier League',
  'form': 'DWWDD',
  'status': 'same',
  'description': 'UEFA Europa League',
  'all': {'played': 38,
   'win': 13,
   'draw': 14,
   'lose': 11,
   'goals': {'for': 51, 'against': 51}},
  'home': {'played': 19,
   'win': 6,
   'draw': 7,
   'lose': 6,
   'goals': {'for': 24, 'against': 26}},
  'away': {'played': 19,
   'win': 7,
   'draw': 7,
   'lose': 5,
   'goals': {'for': 27, 'against': 25}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 13,
  'team': {'id': 45,
   'name': 'Everton',
   'logo': 'https://media.api-sports.io/football/teams/45.png'},
  'points': 48,
  'goalsDiff': -2,
  'group': 'Premier League',
  'form': 'WWWDL',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 11,
   'draw': 15,
   'lose': 12,
   'goals': {'for': 42, 'against': 44}},
  'home': {'played': 19,
   'win': 5,
   'draw': 9,
   'lose': 5,
   'goals': {'for': 26, 'against': 23}},
  'away': {'played': 19,
   'win': 6,
   'draw': 6,
   'lose': 7,
   'goals': {'for': 16, 'against': 21}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 14,
  'team': {'id': 48,
   'name': 'West Ham',
   'logo': 'https://media.api-sports.io/football/teams/48.png'},
  'points': 43,
  'goalsDiff': -16,
  'group': 'Premier League',
  'form': 'WLWDL',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 11,
   'draw': 10,
   'lose': 17,
   'goals': {'for': 46, 'against': 62}},
  'home': {'played': 19,
   'win': 5,
   'draw': 5,
   'lose': 9,
   'goals': {'for': 23, 'against': 34}},
  'away': {'played': 19,
   'win': 6,
   'draw': 5,
   'lose': 8,
   'goals': {'for': 23, 'against': 28}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 15,
  'team': {'id': 33,
   'name': 'Manchester United',
   'logo': 'https://media.api-sports.io/football/teams/33.png'},
  'points': 42,
  'goalsDiff': -10,
  'group': 'Premier League',
  'form': 'WLLLD',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 11,
   'draw': 9,
   'lose': 18,
   'goals': {'for': 44, 'against': 54}},
  'home': {'played': 19,
   'win': 7,
   'draw': 3,
   'lose': 9,
   'goals': {'for': 23, 'against': 28}},
  'away': {'played': 19,
   'win': 4,
   'draw': 6,
   'lose': 9,
   'goals': {'for': 21, 'against': 26}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 16,
  'team': {'id': 39,
   'name': 'Wolves',
   'logo': 'https://media.api-sports.io/football/teams/39.png'},
  'points': 42,
  'goalsDiff': -15,
  'group': 'Premier League',
  'form': 'DLLLW',
  'status': 'same',
  'description': None,
  'all': {'played': 38,
   'win': 12,
   'draw': 6,
   'lose': 20,
   'goals': {'for': 54, 'against': 69}},
  'home': {'played': 19,
   'win': 6,
   'draw': 3,
   'lose': 10,
   'goals': {'for': 27, 'against': 32}},
  'away': {'played': 19,
   'win': 6,
   'draw': 3,
   'lose': 10,
   'goals': {'for': 27, 'against': 37}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 17,
  'team': {'id': 47,
   'name': 'Tottenham',
   'logo': 'https://media.api-sports.io/football/teams/47.png'},
  'points': 38,
  'goalsDiff': -1,
  'group': 'Premier League',
  'form': 'LLLDL',
  'status': 'same',
  'description': 'Champions League',
  'all': {'played': 38,
   'win': 11,
   'draw': 5,
   'lose': 22,
   'goals': {'for': 64, 'against': 65}},
  'home': {'played': 19,
   'win': 6,
   'draw': 3,
   'lose': 10,
   'goals': {'for': 35, 'against': 35}},
  'away': {'played': 19,
   'win': 5,
   'draw': 2,
   'lose': 12,
   'goals': {'for': 29, 'against': 30}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 18,
  'team': {'id': 46,
   'name': 'Leicester',
   'logo': 'https://media.api-sports.io/football/teams/46.png'},
  'points': 25,
  'goalsDiff': -47,
  'group': 'Premier League',
  'form': 'LWDWL',
  'status': 'same',
  'description': 'Relegation',
  'all': {'played': 38,
   'win': 6,
   'draw': 7,
   'lose': 25,
   'goals': {'for': 33, 'against': 80}},
  'home': {'played': 19,
   'win': 4,
   'draw': 3,
   'lose': 12,
   'goals': {'for': 15, 'against': 34}},
  'away': {'played': 19,
   'win': 2,
   'draw': 4,
   'lose': 13,
   'goals': {'for': 18, 'against': 46}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 19,
  'team': {'id': 57,
   'name': 'Ipswich',
   'logo': 'https://media.api-sports.io/football/teams/57.png'},
  'points': 22,
  'goalsDiff': -46,
  'group': 'Premier League',
  'form': 'LLLDL',
  'status': 'same',
  'description': 'Relegation',
  'all': {'played': 38,
   'win': 4,
   'draw': 10,
   'lose': 24,
   'goals': {'for': 36, 'against': 82}},
  'home': {'played': 19,
   'win': 1,
   'draw': 4,
   'lose': 14,
   'goals': {'for': 14, 'against': 44}},
  'away': {'played': 19,
   'win': 3,
   'draw': 6,
   'lose': 10,
   'goals': {'for': 22, 'against': 38}},
  'update': '2025-05-26T00:00:00+00:00'},
 {'rank': 20,
  'team': {'id': 41,
   'name': 'Southampton',
   'logo': 'https://media.api-sports.io/football/teams/41.png'},
  'points': 12,
  'goalsDiff': -60,
  'group': 'Premier League',
  'form': 'LLDLL',
  'status': 'same',
  'description': 'Relegation',
  'all': {'played': 38,
   'win': 2,
   'draw': 6,
   'lose': 30,
   'goals': {'for': 26, 'against': 86}},
  'home': {'played': 19,
   'win': 1,
   'draw': 3,
   'lose': 15,
   'goals': {'for': 13, 'against': 47}},
  'away': {'played': 19,
   'win': 1,
   'draw': 3,
   'lose': 15,
   'goals': {'for': 13, 'against': 39}},
  'update': '2025-05-26T00:00:00+00:00'}]

In [163]:
formatted_standings_list = json.dumps(standings_list, indent=4)
print(f"\n\n\n{formatted_standings_list}")

[
    {
        "rank": 1,
        "team": {
            "id": 40,
            "name": "Liverpool",
            "logo": "https://media.api-sports.io/football/teams/40.png"
        },
        "points": 84,
        "goalsDiff": 45,
        "group": "Premier League",
        "form": "DLDLW",
        "status": "same",
        "description": "Champions League",
        "all": {
            "played": 38,
            "win": 25,
            "draw": 9,
            "lose": 4,
            "goals": {
                "for": 86,
                "against": 41
            }
        },
        "home": {
            "played": 19,
            "win": 14,
            "draw": 4,
            "lose": 1,
            "goals": {
                "for": 42,
                "against": 16
            }
        },
        "away": {
            "played": 19,
            "win": 11,
            "draw": 5,
            "lose": 3,
            "goals": {
                "for": 44,
                "against": 25
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 2,
        "team": {
            "id": 42,
            "name": "Arsenal",
            "logo": "https://media.api-sports.io/football/teams/42.png"
        },
        "points": 74,
        "goalsDiff": 35,
        "group": "Premier League",
        "form": "WWDLD",
        "status": "same",
        "description": "Champions League",
        "all": {
            "played": 38,
            "win": 20,
            "draw": 14,
            "lose": 4,
            "goals": {
                "for": 69,
                "against": 34
            }
        },
        "home": {
            "played": 19,
            "win": 11,
            "draw": 6,
            "lose": 2,
            "goals": {
                "for": 35,
                "against": 17
            }
        },
        "away": {
            "played": 19,
            "win": 9,
            "draw": 8,
            "lose": 2,
            "goals": {
                "for": 34,
                "against": 17
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 3,
        "team": {
            "id": 50,
            "name": "Manchester City",
            "logo": "https://media.api-sports.io/football/teams/50.png"
        },
        "points": 71,
        "goalsDiff": 28,
        "group": "Premier League",
        "form": "WWDWW",
        "status": "same",
        "description": "Champions League",
        "all": {
            "played": 38,
            "win": 21,
            "draw": 8,
            "lose": 9,
            "goals": {
                "for": 72,
                "against": 44
            }
        },
        "home": {
            "played": 19,
            "win": 13,
            "draw": 3,
            "lose": 3,
            "goals": {
                "for": 43,
                "against": 23
            }
        },
        "away": {
            "played": 19,
            "win": 8,
            "draw": 5,
            "lose": 6,
            "goals": {
                "for": 29,
                "against": 21
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 4,
        "team": {
            "id": 49,
            "name": "Chelsea",
            "logo": "https://media.api-sports.io/football/teams/49.png"
        },
        "points": 69,
        "goalsDiff": 21,
        "group": "Premier League",
        "form": "WWLWW",
        "status": "same",
        "description": "Champions League",
        "all": {
            "played": 38,
            "win": 20,
            "draw": 9,
            "lose": 9,
            "goals": {
                "for": 64,
                "against": 43
            }
        },
        "home": {
            "played": 19,
            "win": 12,
            "draw": 5,
            "lose": 2,
            "goals": {
                "for": 35,
                "against": 18
            }
        },
        "away": {
            "played": 19,
            "win": 8,
            "draw": 4,
            "lose": 7,
            "goals": {
                "for": 29,
                "against": 25
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 5,
        "team": {
            "id": 34,
            "name": "Newcastle",
            "logo": "https://media.api-sports.io/football/teams/34.png"
        },
        "points": 66,
        "goalsDiff": 21,
        "group": "Premier League",
        "form": "LLWDW",
        "status": "same",
        "description": "Champions League",
        "all": {
            "played": 38,
            "win": 20,
            "draw": 6,
            "lose": 12,
            "goals": {
                "for": 68,
                "against": 47
            }
        },
        "home": {
            "played": 19,
            "win": 12,
            "draw": 2,
            "lose": 5,
            "goals": {
                "for": 40,
                "against": 20
            }
        },
        "away": {
            "played": 19,
            "win": 8,
            "draw": 4,
            "lose": 7,
            "goals": {
                "for": 28,
                "against": 27
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 6,
        "team": {
            "id": 66,
            "name": "Aston Villa",
            "logo": "https://media.api-sports.io/football/teams/66.png"
        },
        "points": 66,
        "goalsDiff": 7,
        "group": "Premier League",
        "form": "LWWWL",
        "status": "same",
        "description": "UEFA Europa League",
        "all": {
            "played": 38,
            "win": 19,
            "draw": 9,
            "lose": 10,
            "goals": {
                "for": 58,
                "against": 51
            }
        },
        "home": {
            "played": 19,
            "win": 11,
            "draw": 7,
            "lose": 1,
            "goals": {
                "for": 34,
                "against": 20
            }
        },
        "away": {
            "played": 19,
            "win": 8,
            "draw": 2,
            "lose": 9,
            "goals": {
                "for": 24,
                "against": 31
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 7,
        "team": {
            "id": 65,
            "name": "Nottingham Forest",
            "logo": "https://media.api-sports.io/football/teams/65.png"
        },
        "points": 65,
        "goalsDiff": 12,
        "group": "Premier League",
        "form": "LWDDL",
        "status": "same",
        "description": "Conference League Qualification",
        "all": {
            "played": 38,
            "win": 19,
            "draw": 8,
            "lose": 11,
            "goals": {
                "for": 58,
                "against": 46
            }
        },
        "home": {
            "played": 19,
            "win": 9,
            "draw": 5,
            "lose": 5,
            "goals": {
                "for": 26,
                "against": 16
            }
        },
        "away": {
            "played": 19,
            "win": 10,
            "draw": 3,
            "lose": 6,
            "goals": {
                "for": 32,
                "against": 30
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 8,
        "team": {
            "id": 51,
            "name": "Brighton",
            "logo": "https://media.api-sports.io/football/teams/51.png"
        },
        "points": 61,
        "goalsDiff": 7,
        "group": "Premier League",
        "form": "WWWDW",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 16,
            "draw": 13,
            "lose": 9,
            "goals": {
                "for": 66,
                "against": 59
            }
        },
        "home": {
            "played": 19,
            "win": 8,
            "draw": 8,
            "lose": 3,
            "goals": {
                "for": 30,
                "against": 26
            }
        },
        "away": {
            "played": 19,
            "win": 8,
            "draw": 5,
            "lose": 6,
            "goals": {
                "for": 36,
                "against": 33
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 9,
        "team": {
            "id": 35,
            "name": "Bournemouth",
            "logo": "https://media.api-sports.io/football/teams/35.png"
        },
        "points": 56,
        "goalsDiff": 12,
        "group": "Premier League",
        "form": "WLLWD",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 15,
            "draw": 11,
            "lose": 12,
            "goals": {
                "for": 58,
                "against": 46
            }
        },
        "home": {
            "played": 19,
            "win": 8,
            "draw": 4,
            "lose": 7,
            "goals": {
                "for": 23,
                "against": 16
            }
        },
        "away": {
            "played": 19,
            "win": 7,
            "draw": 7,
            "lose": 5,
            "goals": {
                "for": 35,
                "against": 30
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 10,
        "team": {
            "id": 55,
            "name": "Brentford",
            "logo": "https://media.api-sports.io/football/teams/55.png"
        },
        "points": 56,
        "goalsDiff": 9,
        "group": "Premier League",
        "form": "DLWWW",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 16,
            "draw": 8,
            "lose": 14,
            "goals": {
                "for": 66,
                "against": 57
            }
        },
        "home": {
            "played": 19,
            "win": 9,
            "draw": 4,
            "lose": 6,
            "goals": {
                "for": 40,
                "against": 35
            }
        },
        "away": {
            "played": 19,
            "win": 7,
            "draw": 4,
            "lose": 8,
            "goals": {
                "for": 26,
                "against": 22
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 11,
        "team": {
            "id": 36,
            "name": "Fulham",
            "logo": "https://media.api-sports.io/football/teams/36.png"
        },
        "points": 54,
        "goalsDiff": 0,
        "group": "Premier League",
        "form": "LWLLW",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 15,
            "draw": 9,
            "lose": 14,
            "goals": {
                "for": 54,
                "against": 54
            }
        },
        "home": {
            "played": 19,
            "win": 7,
            "draw": 5,
            "lose": 7,
            "goals": {
                "for": 27,
                "against": 30
            }
        },
        "away": {
            "played": 19,
            "win": 8,
            "draw": 4,
            "lose": 7,
            "goals": {
                "for": 27,
                "against": 24
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 12,
        "team": {
            "id": 52,
            "name": "Crystal Palace",
            "logo": "https://media.api-sports.io/football/teams/52.png"
        },
        "points": 53,
        "goalsDiff": 0,
        "group": "Premier League",
        "form": "DWWDD",
        "status": "same",
        "description": "UEFA Europa League",
        "all": {
            "played": 38,
            "win": 13,
            "draw": 14,
            "lose": 11,
            "goals": {
                "for": 51,
                "against": 51
            }
        },
        "home": {
            "played": 19,
            "win": 6,
            "draw": 7,
            "lose": 6,
            "goals": {
                "for": 24,
                "against": 26
            }
        },
        "away": {
            "played": 19,
            "win": 7,
            "draw": 7,
            "lose": 5,
            "goals": {
                "for": 27,
                "against": 25
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 13,
        "team": {
            "id": 45,
            "name": "Everton",
            "logo": "https://media.api-sports.io/football/teams/45.png"
        },
        "points": 48,
        "goalsDiff": -2,
        "group": "Premier League",
        "form": "WWWDL",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 11,
            "draw": 15,
            "lose": 12,
            "goals": {
                "for": 42,
                "against": 44
            }
        },
        "home": {
            "played": 19,
            "win": 5,
            "draw": 9,
            "lose": 5,
            "goals": {
                "for": 26,
                "against": 23
            }
        },
        "away": {
            "played": 19,
            "win": 6,
            "draw": 6,
            "lose": 7,
            "goals": {
                "for": 16,
                "against": 21
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 14,
        "team": {
            "id": 48,
            "name": "West Ham",
            "logo": "https://media.api-sports.io/football/teams/48.png"
        },
        "points": 43,
        "goalsDiff": -16,
        "group": "Premier League",
        "form": "WLWDL",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 11,
            "draw": 10,
            "lose": 17,
            "goals": {
                "for": 46,
                "against": 62
            }
        },
        "home": {
            "played": 19,
            "win": 5,
            "draw": 5,
            "lose": 9,
            "goals": {
                "for": 23,
                "against": 34
            }
        },
        "away": {
            "played": 19,
            "win": 6,
            "draw": 5,
            "lose": 8,
            "goals": {
                "for": 23,
                "against": 28
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 15,
        "team": {
            "id": 33,
            "name": "Manchester United",
            "logo": "https://media.api-sports.io/football/teams/33.png"
        },
        "points": 42,
        "goalsDiff": -10,
        "group": "Premier League",
        "form": "WLLLD",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 11,
            "draw": 9,
            "lose": 18,
            "goals": {
                "for": 44,
                "against": 54
            }
        },
        "home": {
            "played": 19,
            "win": 7,
            "draw": 3,
            "lose": 9,
            "goals": {
                "for": 23,
                "against": 28
            }
        },
        "away": {
            "played": 19,
            "win": 4,
            "draw": 6,
            "lose": 9,
            "goals": {
                "for": 21,
                "against": 26
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 16,
        "team": {
            "id": 39,
            "name": "Wolves",
            "logo": "https://media.api-sports.io/football/teams/39.png"
        },
        "points": 42,
        "goalsDiff": -15,
        "group": "Premier League",
        "form": "DLLLW",
        "status": "same",
        "description": null,
        "all": {
            "played": 38,
            "win": 12,
            "draw": 6,
            "lose": 20,
            "goals": {
                "for": 54,
                "against": 69
            }
        },
        "home": {
            "played": 19,
            "win": 6,
            "draw": 3,
            "lose": 10,
            "goals": {
                "for": 27,
                "against": 32
            }
        },
        "away": {
            "played": 19,
            "win": 6,
            "draw": 3,
            "lose": 10,
            "goals": {
                "for": 27,
                "against": 37
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 17,
        "team": {
            "id": 47,
            "name": "Tottenham",
            "logo": "https://media.api-sports.io/football/teams/47.png"
        },
        "points": 38,
        "goalsDiff": -1,
        "group": "Premier League",
        "form": "LLLDL",
        "status": "same",
        "description": "Champions League",
        "all": {
            "played": 38,
            "win": 11,
            "draw": 5,
            "lose": 22,
            "goals": {
                "for": 64,
                "against": 65
            }
        },
        "home": {
            "played": 19,
            "win": 6,
            "draw": 3,
            "lose": 10,
            "goals": {
                "for": 35,
                "against": 35
            }
        },
        "away": {
            "played": 19,
            "win": 5,
            "draw": 2,
            "lose": 12,
            "goals": {
                "for": 29,
                "against": 30
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 18,
        "team": {
            "id": 46,
            "name": "Leicester",
            "logo": "https://media.api-sports.io/football/teams/46.png"
        },
        "points": 25,
        "goalsDiff": -47,
        "group": "Premier League",
        "form": "LWDWL",
        "status": "same",
        "description": "Relegation",
        "all": {
            "played": 38,
            "win": 6,
            "draw": 7,
            "lose": 25,
            "goals": {
                "for": 33,
                "against": 80
            }
        },
        "home": {
            "played": 19,
            "win": 4,
            "draw": 3,
            "lose": 12,
            "goals": {
                "for": 15,
                "against": 34
            }
        },
        "away": {
            "played": 19,
            "win": 2,
            "draw": 4,
            "lose": 13,
            "goals": {
                "for": 18,
                "against": 46
            }
        },
        "update": "2025-05-26T00:00:00+00:00"
    },
    {
        "rank": 19,
        "team": {
            "id": 57,
            "name": "Ipswich",
            "logo": "https://media.api-sports.io/football/teams/57.png"
        },
        "points": 22,
        "goalsDiff": -46,
        "group": "Premier League",
        "form": "LLLDL",
        "status": "same",
        "description": "Relegation",
        "all": {
            "played": 38,
            "win": 4,
            "draw": 10,
            "lose": 24,
            "goals": {
                "for": 36,
                "against": 82
            }
        },
        "home": {
            "played": 19,
            "win": 1,
            "draw": 4,
            "lose": 14,
            "goals": {
                "for": 14,
                "against": 44
            }
        },
        "away": {
            "played": 19,
            "win": 3,
            "draw": 6,
            "lose": 10,
            "goals": {

In [164]:
rows = []
column_names = ['season', 'position', 'team_id', 'team', 'played', 'won', 'draw', 'lost', 'goal_for', 'goal_against', 'goal_diff', 'points', 'form']

for club in standings_list:
    season          = 2024
    position        = club['rank']
    team_id         = club['team']['id']
    team            = club['team']['name']
    played          = club['all']['played']
    won             = club['all']['win']
    draw            = club['all']['draw']
    lost            = club['all']['lose']
    goals_for       = club['all']['goals']['for']
    goals_against   = club['all']['goals']['against']
    goal_diff       = club['goalsDiff']
    points          = club['points']
    form            = club['form']

    active_row = (season, position, team_id, team, played, won, draw, lost, goals_for, goals_against, goal_diff, points, form)
    rows.append(active_row)

In [165]:
print(rows)

[(2024, 1, 40, 'Liverpool', 38, 25, 9, 4, 86, 41, 45, 84, 'DLDLW'), (2024, 2, 42, 'Arsenal', 38, 20, 14, 4, 69, 34, 35, 74, 'WWDLD'), (2024, 3, 50, 'Manchester City', 38, 21, 8, 9, 72, 44, 28, 71, 'WWDWW'), (2024, 4, 49, 'Chelsea', 38, 20, 9, 9, 64, 43, 21, 69, 'WWLWW'), (2024, 5, 34, 'Newcastle', 38, 20, 6, 12, 68, 47, 21, 66, 'LLWDW'), (2024, 6, 66, 'Aston Villa', 38, 19, 9, 10, 58, 51, 7, 66, 'LWWWL'), (2024, 7, 65, 'Nottingham Forest', 38, 19, 8, 11, 58, 46, 12, 65, 'LWDDL'), (2024, 8, 51, 'Brighton', 38, 16, 13, 9, 66, 59, 7, 61, 'WWWDW'), (2024, 9, 35, 'Bournemouth', 38, 15, 11, 12, 58, 46, 12, 56, 'WLLWD'), (2024, 10, 55, 'Brentford', 38, 16, 8, 14, 66, 57, 9, 56, 'DLWWW'), (2024, 11, 36, 'Fulham', 38, 15, 9, 14, 54, 54, 0, 54, 'LWLLW'), (2024, 12, 52, 'Crystal Palace', 38, 13, 14, 11, 51, 51, 0, 53, 'DWWDD'), (2024, 13, 45, 'Everton', 38, 11, 15, 12, 42, 44, -2, 48, 'WWWDL'), (2024, 14, 48, 'West Ham', 38, 11, 10, 17, 46, 62, -16, 43, 'WLWDL'), (2024, 15, 33, 'Manchester United', 38, 11, 9, 18, 44, 54, -10, 42, 'WLLLD'), (2024, 16, 39, 'Wolves', 38, 12, 6, 20, 54, 69, -15, 42, 'DLLLW'), (2024, 17, 47, 'Tottenham', 38, 11, 5, 22, 64, 65, -1, 38, 'LLLDL'), (2024, 18, 46, 'Leicester', 38, 6, 7, 25, 33, 80, -47, 25, 'LWDWL'), (2024, 19, 57, 'Ipswich', 38, 4, 10, 24, 36, 82, -46, 22, 'LLLDL'), (2024, 20, 41, 'Southampton', 38, 2, 6, 30, 26, 86, -60, 12, 'LLDLL')]

In [166]:
df = pd.DataFrame(rows, columns=column_names)

In [167]:
df.head(20)

,season,position,team_id,team,played,won,draw,lost,goal_for,goal_against,goal_diff,points,form
0,2024,1,40,Liverpool,38,25,9,4,86,41,45,84,DLDLW
1,2024,2,42,Arsenal,38,20,14,4,69,34,35,74,WWDLD
2,2024,3,50,Manchester City,38,21,8,9,72,44,28,71,WWDWW
3,2024,4,49,Chelsea,38,20,9,9,64,43,21,69,WWLWW
4,2024,5,34,Newcastle,38,20,6,12,68,47,21,66,LLWDW
5,2024,6,66,Aston Villa,38,19,9,10,58,51,7,66,LWWWL
6,2024,7,65,Nottingham Forest,38,19,8,11,58,46,12,65,LWDDL
7,2024,8,51,Brighton,38,16,13,9,66,59,7,61,WWWDW
8,2024,9,35,Bournemouth,38,15,11,12,58,46,12,56,WLLWD
9,2024,10,55,Brentford,38,16,8,14,66,57,9,56,DLWWW
10,2024,11,36,Fulham,38,15,9,14,54,54,0,54,LWLLW
11,2024,12,52,Crystal Palace,38,13,14,11,51,51,0,53,DWWDD
12,2024,13,45,Everton,38,11,15,12,42,44,-2,48,WWWDL
13,2024,14,48,West Ham,38,11,10,17,46,62,-16,43,WLWDL
14,2024,15,33,Manchester United,38,11,9,18,44,54,-10,42,WLLLD
15,2024,16,39,Wolves,38,12,6,20,54,69,-15,42,DLLLW
16,2024,17,47,Tottenham,38,11,5,22,64,65,-1,38,LLLDL
17,2024,18,46,Leicester,38,6,7,25,33,80,-47,25,LWDWL
18,2024,19,57,Ipswich,38,4,10,24,36,82,-46,22,LLLDL
19,2024,20,41,Southampton,38,2,6,30,26,86,-60,12,LLDLL

In [168]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season        20 non-null     int64
 1   position      20 non-null     int64
 2   team_id       20 non-null     int64
 3   team          20 non-null     str
 4   played        20 non-null     int64
 5   won           20 non-null     int64
 6   draw          20 non-null     int64
 7   lost          20 non-null     int64
 8   goal_for      20 non-null     int64
 9   goal_against  20 non-null     int64
 10  goal_diff     20 non-null     int64
 11  points        20 non-null     int64
 12  form          20 non-null     str
dtypes: int64(11), str(2)
memory usage: 2.2 KB

---------------- LOAD ----------------------

In [169]:
MYSQL_HOST = os.getenv("MYSQL_HOST")
MYSQL_PORT = os.getenv("MYSQL_PORT")
MYSQL_DATABASE = os.getenv("MYSQL_DATABASE")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")

In [170]:
server_conn = connector.connect(
    host = MYSQL_HOST,
    port = MYSQL_PORT,
    user = MYSQL_USER,
    password = MYSQL_PASSWORD,
    connection_timeout=10,
    autocommit=False,
    raise_on_warnings=True
)

In [171]:
server_cur = server_conn.cursor()
print(f"[Success] -  Connected to MySQL Server")

[Success] -  Connected to MySQL Server

In [172]:
server_cur.close()
server_conn.close()

In [173]:
db_connection = connector.connect(
    host = MYSQL_HOST,
    port = MYSQL_PORT,
    user = MYSQL_USER,
    password = MYSQL_PASSWORD,
    database = MYSQL_DATABASE
)

cur = db_connection.cursor(buffered=True)
print(f"[Success] -  Connected to database")

[Success] -  Connected to database

In [174]:
sql_table = "standings"
cur.execute("SHOW TABLES LIKE %s", (f"{sql_table}",))

if cur.fetchone is None:
    raise SystemExit(f"This table '{sql_table}' is NOT found....please create it")
else:
    print("[SUCCESS]- This table '{sql_table}' exists! Continue to the next phase!")

[SUCCESS]- This table '{sql_table}' exists! Continue to the next phase!

In [175]:
table_col = ['season', 'position', 'team_id', 'team', 'played', 'won', 'draw', 'lost', 'goal_for', 'goal_against', 'goal_diff', 'points', 'form']

standings_df = df[table_col]

In [176]:
standings_df

,season,position,team_id,team,played,won,draw,lost,goal_for,goal_against,goal_diff,points,form
0,2024,1,40,Liverpool,38,25,9,4,86,41,45,84,DLDLW
1,2024,2,42,Arsenal,38,20,14,4,69,34,35,74,WWDLD
2,2024,3,50,Manchester City,38,21,8,9,72,44,28,71,WWDWW
3,2024,4,49,Chelsea,38,20,9,9,64,43,21,69,WWLWW
4,2024,5,34,Newcastle,38,20,6,12,68,47,21,66,LLWDW
5,2024,6,66,Aston Villa,38,19,9,10,58,51,7,66,LWWWL
6,2024,7,65,Nottingham Forest,38,19,8,11,58,46,12,65,LWDDL
7,2024,8,51,Brighton,38,16,13,9,66,59,7,61,WWWDW
8,2024,9,35,Bournemouth,38,15,11,12,58,46,12,56,WLLWD
9,2024,10,55,Brentford,38,16,8,14,66,57,9,56,DLWWW
10,2024,11,36,Fulham,38,15,9,14,54,54,0,54,LWLLW
11,2024,12,52,Crystal Palace,38,13,14,11,51,51,0,53,DWWDD
12,2024,13,45,Everton,38,11,15,12,42,44,-2,48,WWWDL
13,2024,14,48,West Ham,38,11,10,17,46,62,-16,43,WLWDL
14,2024,15,33,Manchester United,38,11,9,18,44,54,-10,42,WLLLD
15,2024,16,39,Wolves,38,12,6,20,54,69,-15,42,DLLLW
16,2024,17,47,Tottenham,38,11,5,22,64,65,-1,38,LLLDL
17,2024,18,46,Leicester,38,6,7,25,33,80,-47,25,LWDWL
18,2024,19,57,Ipswich,38,4,10,24,36,82,-46,22,LLLDL
19,2024,20,41,Southampton,38,2,6,30,26,86,-60,12,LLDLL

In [177]:
standings_records_tuples = standings_df.itertuples(index=False, name=None)

list_of_standings_records_tuples = list(standings_records_tuples)

In [178]:
UPSERT_SQL = f"""
INSERT INTO {sql_table}
(season, position, team_id, team, played, won, draw, lost, goals_for, goals_against, goals_diff, points, form)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) AS src
ON DUPLICATE KEY UPDATE
position         = src.position,
team             = src.team,
played           = src.played,
won              = src.won,
draw             = src.draw,
lost             = src.lost,
goals_for        = src.goals_for,
goals_against    = src.goals_against,
goals_diff       = src.goals_diff,
points           = src.points,
form             = src.form;
"""

In [179]:
no_of_rows_uploaded_to_mysql = len(list_of_standings_records_tuples)

In [180]:
try:
    cur.executemany(UPSERT_SQL, list_of_standings_records_tuples)
    db_connection.commit()
    print(f"[SUCCESS] - Upsert attempted for  {no_of_rows_uploaded_to_mysql} rows!")
except Exception as e:
    db_connection.rollback()
    print (f"[ERROR] - Rolled back due to this ....{e}")
finally:
    cur.close()
    db_connection.close()
    print("All database connections now closed.\n\nClean up completed.")

[SUCCESS] - Upsert attempted for  20 rows!
All database connections now closed.

Clean up completed.